### ISSUE TITLE
Tests not passing

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/n-express#329]
It looks like just a case of hard-coding the expected `x-flag` header string, then changing it to `ft-flag`.

What's the logic underlying the x/ft prefix convention? Is it likely to change again?

```
12 failing

  1) Anonymous Middleware Should provide a firstClickFree model when required:
     AssertionError: expected null to be an object
      at test/anon/anon.test.js:45:46
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1518:8)

  2) simple app should have its own route:
     Error: expected "Vary" matching /X-Flags/i, got "ft-flags, ft-anonymous-user"
      at Test._assertHeader (node_modules/supertest/lib/test.js:213:45)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1518:8)

  3) simple app should be possible to add routers:
     Error: expected "Vary" matching /X-Flags/i, got "ft-flags, ft-anonymous-user"
      at Test._assertHeader (node_modules/supertest/lib/test.js:213:45)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1518:8)

  4) vary middleware set default vary headers:
     Error: expected "vary" of "x-flags, ft-anonymous-user", got "ft-flags, ft-anonymous-user"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1518:8)

  5) vary middleware extend vary header using single value:
     Error: expected "vary" of "x-flags, ft-anonymous-user, test-vary", got "ft-flags, ft-anonymous-user, test-vary"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1518:8)

  6) vary middleware extend vary header using vary method:
     Error: expected "vary" of "x-flags, ft-anonymous-user, test-vary", got "ft-flags, ft-anonymous-user, test-vary"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1518:8)

  7) vary middleware extend vary header using array of values:
     Error: expected "vary" of "x-flags, ft-anonymous-user, test-vary1, test-vary2", got "ft-flags, ft-anonymous-user, test-vary1, test-vary2"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1518:8)

  8) vary middleware won't duplicate vary headers:
     Error: expected "vary" of "x-flags, ft-anonymous-user", got "ft-flags, ft-anonymous-user"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1518:8)

  9) vary middleware extend vary header using a map:
     Error: expected "vary" of "x-flags, ft-anonymous-user, test-vary", got "ft-flags, ft-anonymous-user, test-vary"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1518:8)

  10) vary middleware unset single vary header:
     Error: expected "vary" of "x-flags, ft-anonymous-user", got "ft-flags, ft-anonymous-user"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1518:8)

  11) vary middleware unset all vary headers needed by the wrapper layout:
     Error: expected "vary" of "x-flags", got "ft-flags"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1518:8)

  12) vary middleware co-mingle extending and unsetting vary headers:
     Error: expected "vary" of "x-flags, ft-anonymous-user, test-vary", got "ft-flags, ft-anonymous-user, test-vary"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1518:8)
```

**Comment by adambraimbridge** [comment]
No idea WTF is going on here. Local tests and CI tests are conflicting

See https://github.com/Financial-Times/n-express/pull/330:
```
  12 failing

  1) Anonymous Middleware Should provide a firstClickFree model when required:
     AssertionError: expected null to be an object
      at test/anon/anon.test.js:45:46
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)

  2) simple app should have its own route:
     Error: expected "Vary" matching /FT-Flags/i, got "x-flags, ft-anonymous-user"
      at Test._assertHeader (node_modules/supertest/lib/test.js:213:45)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)

  3) simple app should be possible to add routers:
     Error: expected "Vary" matching /FT-Flags/i, got "x-flags, ft-anonymous-user"
      at Test._assertHeader (node_modules/supertest/lib/test.js:213:45)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)

  4) vary middleware set default vary headers:
     Error: expected "vary" of "ft-flags, ft-anonymous-user", got "x-flags, ft-anonymous-user"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)

  5) vary middleware extend vary header using single value:
     Error: expected "vary" of "ft-flags, ft-anonymous-user, test-vary", got "x-flags, ft-anonymous-user, test-vary"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)

  6) vary middleware extend vary header using vary method:
     Error: expected "vary" of "ft-flags, ft-anonymous-user, test-vary", got "x-flags, ft-anonymous-user, test-vary"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)

  7) vary middleware extend vary header using array of values:
     Error: expected "vary" of "ft-flags, ft-anonymous-user, test-vary1, test-vary2", got "x-flags, ft-anonymous-user, test-vary1, test-vary2"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)

  8) vary middleware won't duplicate vary headers:
     Error: expected "vary" of "ft-flags, ft-anonymous-user", got "x-flags, ft-anonymous-user"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)

  9) vary middleware extend vary header using a map:
     Error: expected "vary" of "ft-flags, ft-anonymous-user, test-vary", got "x-flags, ft-anonymous-user, test-vary"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)

  10) vary middleware unset single vary header:
     Error: expected "vary" of "ft-flags, ft-anonymous-user", got "x-flags, ft-anonymous-user"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)

  11) vary middleware unset all vary headers needed by the wrapper layout:
     Error: expected "vary" of "ft-flags", got "x-flags"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)

  12) vary middleware co-mingle extending and unsetting vary headers:
     Error: expected "vary" of "ft-flags, ft-anonymous-user, test-vary", got "x-flags, ft-anonymous-user, test-vary"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)



make: *** [unit-test] Error 1

make test returned exit code 2
```

**Comment by adambraimbridge** [comment]
Aaaah, the old rebuild-without-cache trick. https://circleci.com/gh/Financial-Times/n-express/263
